### PR TITLE
fix: don't attach default sg

### PR DESCRIPTION
**Pull request by jor2**
### Description

Do not attach default security group to vsi when `security_group_ids` is defined.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

If a value is passed for `security_group_ids`, the module will no longer assign the default security group to the VSI, just the ones passed in the `security_group_ids` list. If `create_security_group` is set to false, then the default security group will be attached.<br>NOTE: If upgrading from a previous version, and passing in a value for `security_group_ids`, the module will do an update in place to remove the default security group from the VSI.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by ocofaigh — APPROVED** [review]

**Comment by jor2** [comment]
Need to test
````
Do we know what happens to an existing deployment with that change. Does the default security group get removed from the VSI?
````

**Comment by jor2** [comment]
> Need to test
> 
> ```
> Do we know what happens to an existing deployment with that change. Does the default security group get removed from the VSI?
> ```

Created one with default sg initially then updated terraform to apply a new sg i created and remove default and all worked as expected.
Screenshot 2023-10-12 at 11 18 51

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
