### PR TITLE
fix: update test

### PR DESCRIPTION
**Pull request by maheshwarishikha**
### Description

Updates test

### Release required?

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

### CODE REVIEW

**Comment by rajatagarwal-ibm** [comment]
@maheshwarishikha we do not need this import as "testhelper" is already imported on the pr_test.go. Go lang shares imports at the same directory level.

**Comment by maheshwarishikha** [comment]
> @maheshwarishikha we do not need this import as "testhelper" is already imported in the pr_test.go. Go lang shares imports at the same directory level.

When I run local as below, I hit the same error.
```
% make run-tests-local RUN=TestRunBasicExample      
cd tests && go test -run TestRunBasicExample -count=1 -v -timeout 300m
# github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vsi [github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vsi.test]
./other_test.go:12:13: undefined: testhelper
FAIL	github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vsi [build failed]
make: *** [run-tests-local] Error 1
```

And after importing that library, error is resolved.

**Comment by rajatagarwal-ibm** [comment]
@maheshwarishikha I do not encounter that error.

**Comment by ocofaigh** [comment]
Maybe it is because you are explicitly running that test `make run-tests-local RUN=TestRunBasicExample`. Does it work if you just run `make run-tests-local` ?

**Comment by rajatagarwal** [comment]
@ocofaigh i ran exactly that same test

**Comment by maheshwarishikha** [comment]
@ocofaigh currently there is no existing policy in Dev account `block storage -> HPCS` but test is still failing with the error  `auth policy exists`. Is it something related to upgrade test specifically? otherwise what else.... 🤔

**Comment by ocofaigh** [comment]
@maheshwarishikha If the standard test and the upgrade test are trying to create the same auth policy, then yes we will face this issue. How about running one of the tests with key protect, and the other with hpcs so they don't clash?

**Comment by maheshwarishikha** [comment]
> @ocofaigh Regardless if we have that import in both files it would fail with an "unused import" error.
> 
> ```
> 4197 ± make run-tests-local                                                                                                                          ✹
> cd tests && go test -run '' -count=1 -v -timeout 300m
> # github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vsi [github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vsi.test]
> ./other_test.go:7:2: "github.com/terraform-ibm-modules/ibmcloud-terratest-wrapper/testhelper" imported and not used
> FAIL    github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vsi [build failed]
> make: *** [run-tests-local] Error 1
> ```

Are you trying out with the latest code? Because the new code has bee added in other_test.go that uses testhelper library.

**Comment by ocofaigh** [comment]
@maheshwarishikha I believe you are correct - I think this change is needed. Without it I get:
```
 % make run-tests-local RUN=TestRunBasicExample 
cd tests && go test -run TestRunBasicExample -count=1 -v -timeout 300m
# github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vsi [github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vsi.test]
./other_test.go:13:13: undefined: testhelper
FAIL	github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vsi [build failed]
make: *** [run-tests-local] Error 1
```

**Comment by maheshwarishikha** [comment]
> @maheshwarishikha If the standard test and the upgrade test are trying to create the same auth policy, then yes we will face this issue. How about running one of the tests with key protect, and the other with hpcs so they don't clash? We could update the example to handle both so we just need 1 example. but the tests trigger it differently

hmm..yes, that could be the reason. I'll check tests.

**Comment by maheshwarishikha** [comment]
@ocofaigh 
I think example will handle any KMS. So as such no update required for example. One test can be configured with HPCS and another one with KMS. Will test it. 

Got one question - Dont we use have existing KP instance for any test? If yes, where are the details of KP instance stored? I do not find KP details at common-dev-assets/common-go-assets/common-permanent-resources.yaml

**Comment by ocofaigh** [comment]
@maheshwarishikha We don't have a permanent Key Protect instance. We just create one in the examples. That way we always have a unique instance ID and full end to end examples. This also mans Key Protect auth policies won't clash since its a unique instance every time

**Comment by ocofaigh** [comment]
So can we have the standard test using HPCS and the upgrade test using Key Protect? That way there won't be any clashes

**Comment by maheshwarishikha** [comment]
> So can we have the standard test using HPCS and the upgrade test using Key Protect? That way there won't be any clashes

It can be done. In this case, the example needs modification such that it will create KP instance, auth policy, keys etc if kms_does_not_exist already. 

On a lighter note, how much it helps if we do this additional work in example just for PR test? why not to run test sequentially that also takes care of this clash policy issue?

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
