### PR TITLE
fix: add tags to resources

### PR DESCRIPTION
**Pull request by argeiger**
### Description

This fix adds tags to resources within the VSI which are passed into the module

**Tick the relevant boxes:**
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Examples / tests (addition or updates of examples or tests)
- [ ] Documentation update
- [ ] CI related update (pipeline, etc)

### Checklist:

- [ ] If relevant, a test for the change has been added / updated as part of this PR.
- [ ] If relevant, documentation for the change has been added / updated as part of this PR.

### Merge:
Merge using "Squash and merge" and ensure to use a relevant [conventional commit](https://www.conventionalcommits.org/) message based on the PR contents (this ultimately determines if a new version of the modules needs to be released, and if so, which semver number should be used).

### CODE REVIEW

**Comment by ocofaigh** [comment]
@argeiger @vburckhardt Do you guys think there will ever be a need to create different tags per resource type? 
For example, in this PR the values in `var.tags` will be used to tag the vsi, the vsi fips and the volume. Do you foresee a use case where maybe we would need to add a different tag for one of these?

**Comment by argeiger** [comment]
@ocofaigh correct on that it tags all resources with tags passed in.  I think this is a good start for the tagging aspect since if we were to do each additional component, it will introduce a variable per resource.  This variable could be the base tag and if we introduce additional tagging on per resource, it can append to this.

**Comment by ocofaigh** [comment]
Yes I agree, we can go with this approach as a start and then if needed, we could add extra tag variables per resource later on

**Comment by ocofaigh** [comment]
Hmm, the pipeline failed with:
```
Error: [0m Error: [ERROR] Instance (0737_736b4530-5815-4f56-8efa-6c8040492cbf) went into failed state during the operation 
│  ([
│     {
│         "code": "cannot_start_compute",
│         "message": "Can't start instance because provisioning failed.",
│         "more_info": "https://cloud.ibm.com/docs/vpc?topic=vpc-instance-status-messages#cannot-start-compute"
│     },
│     {
│         "code": "cannot_start_compute",
│         "message": "Can't start instance because provisioning failed.",
│         "more_info": "https://cloud.ibm.com/docs/vpc?topic=vpc-instance-status-messages#cannot-start-compute"
│     }
│ ]) 
│  [WARNING] Running terraform apply again will remove the tainted instance and attempt to create the instance again replacing the previous configuration
│ 
│   with module.slz_vsi.ibm_is_instance.vsi["slz-vsi-s7ojiv-3"],
│   on ../../main.tf line 66, in resource "ibm_is_instance" "vsi":
│   66: resource "ibm_is_instance" "vsi" {
│ 
╵}
```

Re-running to see if it happens again..

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
