### PR TITLE
update basic example to deploy additional data volumes + exposed access tag support in fscloud profile

### PR DESCRIPTION
**Pull request by ocofaigh**
### Description

- Plugged the test gap where we had no example of adding an additional data volume - its now done in fscloud example
- Renamed the default example to basic (since its not longer using all default values now that we pass additional data volumes to it) and moved it into the other_test.go
- Updated pr_test.go to run the fscloud example only (both standard and upgrade)
- Updated CRA to scan fscloud profile
- Added access tag support to fscloud profile and example. Because of this, I need to skip upgrade test since it fails with:
```
│ Error: Value for undeclared variable
│ 
│ A variable named "access_tags" was assigned on the command line, but the
│ root module does not declare a variable of that name. To use this value,
│ add a "variable" block to the configuration.
╵}
```

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

### CODE REVIEW

**Comment by ocofaigh** [comment]
Need to merge https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vsi/pull/513 first so we can update the CRA directory

**Review by jor2 — APPROVED** [review]
LGTM

**Pull request merged**
