### PR TITLE
feat: add padding to the vsi name

### PR DESCRIPTION
**Pull request by Aashiq-J**
### Description

Issue: https://github.ibm.com/GoldenEye/issues/issues/5815

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

### CODE REVIEW

**Comment by Aashiq-J** [comment]
@ocofaigh , The name change is causing the terraform to destroy and recreate the vsi and the block volumes. While rename without destroy is possible from UI, cli or API https://cloud.ibm.com/docs/vpc?topic=vpc-managing-virtual-server-instances&interface=ui#rename-virtual-server-instances-ui . Any idea on how we manage this situation?

**Comment by ocofaigh** [comment]
@Aashiq-J Can you check if its possible to rename using the api? If that works, we need to check provider code to see why it is trying to destroy and recreate. If it doesn't work with api, then we need to reach our to VPC VSI team to see what they recommend for renaming using automation

**Comment by shemau** [comment]
@Aashiq-J I wonder if there is something going on between the storage and the VSI. The VSI probably need recreating because the storage is recreated. If you run this locally, can you see what forces a new resource in the output? 
Alternatively can we rename the storage (without updating the VSI)? Or can we rename the VSI without renaming the storage (which is the one step that the documentation says you can do in the UI)?

https://cloud.ibm.com/docs/vpc?topic=vpc-instance-storage-provisioning&interface=ui does not mention renaming, but https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_volume does not list a name change as `forces new`.

https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_volume boot_volume.volume_id is forces new, so this might trigger the VSI recreate IF there is a volume recreate (I am not sure if the module uses the volumes for boot volumes).

**Comment by Aashiq-J** [comment]
@ocofaigh , @shemau 

I was able to change the name of the vsi and block storage using API and the UI.
```
curl -X PATCH "https://us-south.iaas.cloud.ibm.com/v1/instances/0717_b89cfc4e-ddd7-4618-b95d-90b08b0ac0de?version=2021-06-29&generation=2" -H "Authorization: $iam_token" -d '{"name": "my-instance"}'
```

```

curl -X PATCH "https://us-south.iaas.cloud.ibm.com/v1/volumes/r006-4f29babb-bf77-4414-9035-f0cdb231c546?version=2022-04-22&generation=2" -H "Authorization: $iam_token" -d '{       
      "name": "my-volume-4-update"
    }'
```

There was no other effect on the VSI and the block storage attached to the VSI other than the updated name. In our case the ID remains the same, only the name of the VSI and storage changes.

**Comment by ocofaigh** [comment]
@Aashiq-J ok thats good - so can we create a very basic example (using the ibm provider directly) where we can easily reproduce the rename causing destroy / recreate? Then we can create a provider issue for that.

**Comment by shemau** [comment]
terraform plan from this branch AFTER creating on main branch:

```hcl
# module.slz_vsi.ibm_is_instance.vsi["slz-vsi-001"] will be created
  + resource "ibm_is_instance" "vsi" {
      + access_tags                       = (known after apply)
      + availability_policy_host_failure  = (known after apply)
      + bandwidth                         = (known after apply)
      + crn                               = (known after apply)
      + default_trusted_profile_auto_link = (known after apply)
      + disks                             = (known after apply)
      + force_action                      = false
```

So actually it is getting destroyed and recreated because the name in the map changes. This has nothing to do with the provider. Terraform sees it as a new different map entries.

This adds a whole new dimension. The point of the PR appears to be that the resources created have different names. Therefor can we keep the internal names module.slz_vsi.ibm_is_instance.vsi["slz-vsi-1"] as a reference to `vsi.name: "slz-vsi-001"`? Or is that just even more confusing?

**Comment by Aashiq-J** [comment]
@shemau Thanks for your input, keeping the map keys the same solved our issue. Now its updating the name of the instances and volumes without recreating.

**Comment by ocofaigh** [comment]
Looks good folks, nice work. @Aashiq-J please update the release notes section of the PR description and ensure we include info about the expected (non disruptive) rename

**Comment by ocofaigh** [comment]
@shemau Since Aashiq is out, would you be able to create the release notes for this update please? And I can look after getting them into a release

**Comment by ocofaigh** [comment]
As expected, the upgrade test is failing with these identified updates:
```
Messages:   	Resource(s) identified to be updated Name: vsi Address: module.slz_vsi.module.fscloud_vsi.ibm_is_instance.vsi["slz-vsi-upg-mpqhal-1"] Actions: [update]
        	            	DIFF:
        	            	Before: {"name":"slz-vsi-upg-mpqhal-1"}
        	            	After: {"name":"slz-vsi-upg-mpqhal-001"}
```
```
Messages:   	Resource(s) identified to be updated Name: vsi Address: module.slz_vsi.module.fscloud_vsi.ibm_is_instance.vsi["slz-vsi-upg-mpqhal-2"] Actions: [update]
        	            	DIFF:
        	            	Before: {"name":"slz-vsi-upg-mpqhal-2"}
        	            	After: {"name":"slz-vsi-upg-mpqhal-002"}
```
```
Messages:   	Resource(s) identified to be updated Name: vsi Address: module.slz_vsi.module.fscloud_vsi.ibm_is_instance.vsi["slz-vsi-upg-mpqhal-3"] Actions: [update]
        	            	DIFF:
        	            	Before: {"name":"slz-vsi-upg-mpqhal-3"}
        	            	After: {"name":"slz-vsi-upg-mpqhal-003"}
```
```
Messages:   	Resource(s) identified to be updated Name: volume Address: module.slz_vsi.module.fscloud_vsi.ibm_is_volume.volume["slz-vsi-upg-mpqhal-3-slz-vsi-upg-mpqhal"] Actions: [update]
        	            	DIFF:
        	            	Before: {"name":"slz-vsi-upg-mpqhal-3-slz-vsi-upg-mpqhal"}
        	            	After: {"name":"slz-vsi-upg-mpqhal-003-slz-vsi-upg-mpqhal"}
```
```
Messages:   	Resource(s) identified to be updated Name: volume Address: module.slz_vsi.module.fscloud_vsi.ibm_is_volume.volume["slz-vsi-upg-mpqhal-1-slz-vsi-upg-mpqhal"] Actions: [update]
        	            	DIFF:
        	            	Before: {"name":"slz-vsi-upg-mpqhal-1-slz-vsi-upg-mpqhal"}
        	            	After: {"name":"slz-vsi-upg-mpqhal-001-slz-vsi-upg-mpqhal"}
```
```
Messages:   	Resource(s) identified to be updated Name: volume Address: module.slz_vsi.module.fscloud_vsi.ibm_is_volume.volume["slz-vsi-upg-mpqhal-2-slz-vsi-upg-mpqhal"] Actions: [update]
        	            	DIFF:
        	            	Before: {"name":"slz-vsi-upg-mpqhal-2-slz-vsi-upg-mpqhal"}
        	            	After: {"name":"slz-vsi-upg-mpqhal-002-slz-vsi-upg-mpqhal"}
```

As these are all expected, and non-disruptive, I will skip upgrade test.

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
