### PR TITLE
chore(deps): update ci dependencies

### PR DESCRIPTION
**Pull request by Aashiq-J**
### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by Aashiq-J** [comment]
Screenshot 2024-07-24 at 1 27 25 PM
The changes are update in place.

**Comment by ocofaigh** [comment]
@Aashiq-J Why are we ignoring this now?? The consistency check is to ensure the module is idempotent, and if it fails we need to know why, and not just ignore it

**Comment by Aashiq-J** [comment]
@ocofaigh ,This is similar to this [provider bug](https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4719),
created a new provider [issue](https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5527) for this.
This error is causing all PR and continuous pipelines to fail for this module.

**Comment by toddgiguere** [comment]
@Aashiq-J @ocofaigh I think we are going to have to add these ignores this way, at least until the provider fixes this idempotent issue. When looking at testwrapper, it only supports identification of updates (and ignoring those updates) at the resource level, not the attribute level.

**Review by toddgiguere — APPROVED** [review]

**Pull request merged**
