### PR TITLE
test: update reference from key-protect to kms

### PR DESCRIPTION
**Pull request by MatthewLemmond**
### Description
Update from `terraform-ibm-key-protect-all-inclusive` to `terraform-ibm-kms-all-inclusive`

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by toddgiguere — APPROVED** [review]

**Review by toddgiguere — APPROVED** [review]

**Comment by ocofaigh** [comment]
The upgrade test failed as it detected an update. Perhaps its expected, but either way its an update to the example here not the module, so suggest just skipping upgrade test

```
Messages:   	Resource(s) identified to be updated 
        	            	Name: key_protect_instance
        	            	Address: module.key_protect_all_inclusive.module.key_protect[0].ibm_resource_instance.key_protect_instance
        	            	Actions: [update]
        	            	DIFF:
        	            	  Before: 
        	            		{"parameters":"SECURE_VALUE_HIDDEN_HASH:-de4b141dd0d97d7ad9ad917dae0f53ee76c351556d0f2a5049b2f444"}
        	            	  After: 
        	            		{"parameters":"SECURE_VALUE_HIDDEN_HASH:-829963295c3296b7551f1366e374de4d3c31c2ee290fa85f86237868"}
```

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
