### PR TITLE
fix: fix bug where floating IPs were incorrectly getting created in the default resource group

### PR DESCRIPTION
**Pull request by ocofaigh**
### Description

fix bug where floating IPs were incorrectly getting created in the default resource group

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [x] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by daniel-butler-irl — DISMISSED** [review]

**Comment by ocofaigh** [comment]
As expected, the upgrade test is failing because it want to delete the FIP and recreate it in the correct resource group:
```
Messages:   	Resource(s) identified to be destroyed 
        	            	Name: vsi_fip
        	            	Address: module.slz_vsi.ibm_is_floating_ip.vsi_fip["slz-vsi-com-upg-snp3jm-2"]
        	            	Actions: [delete create]
        	            	DIFF:
        	            	  Before: 
        	            		{"address":"52.118.252.13","crn":"crn:v1:bluemix:public:is:us-south-2:a/abac0df06b644a9cabc6e44f55b3880e::floating-ip:r006-43ea41d4-1cb6-4633-8f0f-ad41787e914c","id":"r006-43ea41d4-1cb6-4633-8f0f-ad41787e914c","resource_controller_url":"https://cloud.ibm.com/vpc-ext/network/floatingIPs","resource_crn":"crn:v1:bluemix:public:is:us-south-2:a/abac0df06b644a9cabc6e44f55b3880e::floating-ip:r006-43ea41d4-1cb6-4633-8f0f-ad41787e914c","resource_group":"07b6d899988a4631841e3bc7d0307dcf","resource_group_name":"Default","resource_name":"slz-vsi-com-upg-snp3jm-002-fip","resource_status":"available","status":"available","tags":"SECURE_VALUE_HIDDEN_HASH:-88bfbee55f25bc5d76f3ed9314d40cf5bb29857cd739798a6462d5a2","target_list":"SECURE_VALUE_HIDDEN_HASH:-9fffae1ea24f7961294f48693a1f82d8eac10bf397fbd08a8e255513","zone":"us-south-2"}
        	            	  After: 
        	            		{"resource_group":"292170bc79c94f5e9019e46fb48f245a"}
```

I'm thinking maybe this should mandate a major version release

**Pull request merged**
